// Generated by scripts/extract-fields.py — do not edit by hand.
// Per painting: the sampled colour used as its block-in field, and
// its true proportions, so plates are framed to the work.
// Rerun after adding paintings:  python3 scripts/extract-fields.py

export interface PaintingMeta {
  field: string;
  ratio: number;
}

export const PAINTING_META: Record<string, PaintingMeta> = {
  "/paintings/abstract-landscape/gabriel_one.jpg": { field: "#998F6C", ratio: 1.0306 },
  "/paintings/abstract-landscape/gabriel_two.jpg": { field: "#988958", ratio: 0.9939 },
  "/paintings/abstract-landscape/tuscany_five.jpg": { field: "#976B4F", ratio: 0.9777 },
  "/paintings/abstract-landscape/tuscany_four.jpg": { field: "#A46657", ratio: 0.998 },
  "/paintings/abstract-landscape/tuscany_one.jpg": { field: "#9E985F", ratio: 0.7497 },
  "/paintings/abstract-landscape/tuscany_seven.jpg": { field: "#364352", ratio: 1.0004 },
  "/paintings/abstract-landscape/tuscany_six.jpg": { field: "#90874B", ratio: 0.9715 },
  "/paintings/abstract-landscape/tuscany_three.jpg": { field: "#A68056", ratio: 0.7497 },
  "/paintings/abstract-landscape/tuscany_two.jpg": { field: "#B8A06A", ratio: 0.7497 },
  "/paintings/houses/20th-street.jpg": { field: "#664E40", ratio: 1.3568 },
  "/paintings/houses/32nd-street.jpg": { field: "#524D4B", ratio: 1.3333 },
  "/paintings/houses/4th-street.jpg": { field: "#767A3F", ratio: 1.3793 },
  "/paintings/houses/adams-street.jpg": { field: "#B5B4B3", ratio: 1.3333 },
  "/paintings/houses/argonne.jpg": { field: "#715F5A", ratio: 1.3333 },
  "/paintings/houses/bank-building-division-street.jpg": { field: "#BB9061", ratio: 1.3534 },
  "/paintings/houses/bower.jpg": { field: "#4D3A52", ratio: 1.3602 },
  "/paintings/houses/braeburn.jpg": { field: "#524F4E", ratio: 1.3333 },
  "/paintings/houses/dearborn-street.jpg": { field: "#814347", ratio: 1.3758 },
  "/paintings/houses/eagle-ridge.jpg": { field: "#B7B3B1", ratio: 1.3333 },
  "/paintings/houses/faculty-club-carleton-college.jpg": { field: "#776840", ratio: 1.3466 },
  "/paintings/houses/friar-tuck.jpg": { field: "#505052", ratio: 1.3333 },
  "/paintings/houses/goodhue.jpg": { field: "#73483C", ratio: 1.3619 },
  "/paintings/houses/hendricks-street.jpg": { field: "#525252", ratio: 1.3333 },
  "/paintings/houses/illinois-street.jpg": { field: "#5E504F", ratio: 1.3333 },
  "/paintings/houses/lucretia-court.jpg": { field: "#74493C", ratio: 1.3671 },
  "/paintings/houses/macleay-gardens.jpg": { field: "#AF985B", ratio: 1.35 },
  "/paintings/houses/maplewood-road.jpg": { field: "#AB8B59", ratio: 1.34 },
  "/paintings/houses/molina.jpg": { field: "#52524E", ratio: 1.3333 },
  "/paintings/houses/naito-parkway.jpg": { field: "#524E4D", ratio: 1.3333 },
  "/paintings/houses/pacific-ave.jpg": { field: "#AD985A", ratio: 1.3688 },
  "/paintings/houses/ridgeway-drive.jpg": { field: "#525252", ratio: 1.3333 },
  "/paintings/houses/robin-hood.jpg": { field: "#663835", ratio: 1.4008 },
  "/paintings/houses/vancouver-ave.jpg": { field: "#C7A767", ratio: 1.3466 },
  "/paintings/houses/watson-hall.jpg": { field: "#786743", ratio: 1.3602 },
  "/paintings/sketches/iguana.jpeg": { field: "#8A6548", ratio: 1.3281 },
  "/paintings/sketches/not_lake_house.jpg": { field: "#91ACC7", ratio: 1.9566 },
  "/paintings/sketches/tuscany_study_1.jpg": { field: "#9F7F53", ratio: 2.0468 },
  "/paintings/sketches/tuscany_study_2.jpg": { field: "#625E5D", ratio: 0.9243 },
  "/paintings/sketches/tuscany_study_3.jpg": { field: "#C7A767", ratio: 2.0963 },
  "/paintings/sketches/tuscany_study_4.jpg": { field: "#393E52", ratio: 1.0391 },
};

// Fallbacks for anything not yet sampled: the slate out of Tuscany Four.
export const DEFAULT_FIELD = "#55647D";
export const DEFAULT_RATIO = 4 / 3;

export function fieldFor(imagePath: string): string {
  return PAINTING_META[imagePath]?.field ?? DEFAULT_FIELD;
}

export function ratioFor(imagePath: string): number {
  return PAINTING_META[imagePath]?.ratio ?? DEFAULT_RATIO;
}
