-- Sampled presentation data for each painting. Both are derived from the
-- image by scripts/sample-paintings.py and travel in the manifests, so they
-- are regenerated by a reseed like every other field.
ALTER TABLE "Painting" ADD COLUMN "field" TEXT;
ALTER TABLE "Painting" ADD COLUMN "ratio" REAL;
