#!/usr/bin/env python3
"""Sample one signature colour and the true proportions of each painting.

The site's block-in state paints each image as a flat field of colour before
the photograph resolves in. Those fields are not chosen by hand — they are
sampled from the painting itself, so the palette is always honestly the
work's own.

Naive dominant-colour extraction is useless here: these are photographs of
paint on paper, so the most common colours are all paper. We quantise, throw
away anything too pale or too dark to read as a field, and then rank what is
left by area weighted toward saturation — which is how you would name a
painting's colour out loud.

The aspect ratio is recorded at the same time so gallery plates can be framed
to the work rather than letterboxed into a uniform box.

Usage:  python3 scripts/extract-fields.py
Writes: app/lib/paintingFields.ts
"""

import colorsys
import json
import pathlib
import sys

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow is required:  pip install Pillow")

ROOT = pathlib.Path(__file__).resolve().parent.parent
MANIFESTS = sorted((ROOT / "content" / "paintings").glob("*.json"))
OUT = ROOT / "app" / "lib" / "paintingFields.ts"

# Fields that are nearly white or nearly black read as paper or as a hole in
# the page, not as colour, so they are out of the running.
MIN_SATURATION = 0.20
VALUE_RANGE = (0.20, 0.90)
SATURATION_BIAS = 1.6  # >1 favours chroma over sheer area

# Some of these are photographs taken under warm light, and a few of the
# graphite drawings sample a colour far louder than anything in the site's
# palette. Keep each painting's own hue, but pull chroma and value back into
# the band the rest of the design lives in so the block-in stays on key.
MAX_SATURATION = 0.48
FIELD_VALUE_RANGE = (0.32, 0.78)


def harmonise(hex_code: str) -> str:
    r, g, b = (int(hex_code[i : i + 2], 16) / 255 for i in (1, 3, 5))
    hue, saturation, value = colorsys.rgb_to_hsv(r, g, b)
    saturation = min(saturation, MAX_SATURATION)
    value = min(max(value, FIELD_VALUE_RANGE[0]), FIELD_VALUE_RANGE[1])
    r, g, b = colorsys.hsv_to_rgb(hue, saturation, value)
    return "#%02X%02X%02X" % (round(r * 255), round(g * 255), round(b * 255))


def sample(path: pathlib.Path) -> tuple[str, float]:
    image = Image.open(path).convert("RGB")
    ratio = round(image.width / image.height, 4)
    image.thumbnail((200, 200))
    quantised = image.quantize(colors=48, method=Image.MEDIANCUT).convert("RGB")

    best_score, best_hex = -1.0, None
    fallback_score, fallback_hex = -1.0, "#8A8578"

    for count, (r, g, b) in quantised.getcolors(1 << 20):
        _, saturation, value = colorsys.rgb_to_hsv(r / 255, g / 255, b / 255)
        hex_code = "#%02X%02X%02X" % (r, g, b)

        # Keep the largest region as a fallback for near-monochrome work
        # (the graphite drawings, mostly) so nothing ends up without a field.
        if count > fallback_score:
            fallback_score, fallback_hex = count, hex_code

        if saturation < MIN_SATURATION:
            continue
        if not VALUE_RANGE[0] < value < VALUE_RANGE[1]:
            continue

        score = count * (saturation**SATURATION_BIAS)
        if score > best_score:
            best_score, best_hex = score, hex_code

    return harmonise(best_hex or fallback_hex), ratio


def main() -> None:
    sampled: dict[str, tuple[str, float]] = {}

    for manifest in MANIFESTS:
        for entry in json.loads(manifest.read_text()):
            image_path = entry["imagePath"]
            on_disk = ROOT / "public" / image_path.lstrip("/")
            if not on_disk.exists():
                print(f"  missing  {image_path}", file=sys.stderr)
                continue
            sampled[image_path] = sample(on_disk)
            field, ratio = sampled[image_path]
            print(f"  {field}  {ratio:<7}  {image_path}")

    body = "\n".join(
        f'  "{path}": {{ field: "{field}", ratio: {ratio} }},'
        for path, (field, ratio) in sorted(sampled.items())
    )
    OUT.write_text(
        "// Generated by scripts/extract-fields.py — do not edit by hand.\n"
        "// Per painting: the sampled colour used as its block-in field, and\n"
        "// its true proportions, so plates are framed to the work.\n"
        "// Rerun after adding paintings:  python3 scripts/extract-fields.py\n\n"
        "export interface PaintingMeta {\n"
        "  field: string;\n"
        "  ratio: number;\n"
        "}\n\n"
        "export const PAINTING_META: Record<string, PaintingMeta> = {\n"
        f"{body}\n"
        "};\n\n"
        "// Fallbacks for anything not yet sampled: the slate out of Tuscany Four.\n"
        'export const DEFAULT_FIELD = "#55647D";\n'
        "export const DEFAULT_RATIO = 4 / 3;\n\n"
        "export function fieldFor(imagePath: string): string {\n"
        "  return PAINTING_META[imagePath]?.field ?? DEFAULT_FIELD;\n"
        "}\n\n"
        "export function ratioFor(imagePath: string): number {\n"
        "  return PAINTING_META[imagePath]?.ratio ?? DEFAULT_RATIO;\n"
        "}\n"
    )
    print(f"\n{len(sampled)} paintings -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
